# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint, type-check and test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  test:
    name: test ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
    steps:
      - name: Setup python for tox
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install tox
        run: python -m pip install tox
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Pick environment to run
        run: |
          import os; import platform; import sys; from pathlib import Path
          env = f'TOXENV=py{"" if platform.python_implementation() == "CPython" else "py"}3{sys.version_info.minor}'
          print(f"Picked: {env} for {sys.version} based of {sys.executable}")
          with Path(os.environ["GITHUB_ENV"]).open("ta") as file_handler:
               file_handler.write(env)
        shell: python
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run test suite
        run: tox r --skip-pkg-install
